# fly.toml app configuration file generated for freshowband on 2024-10-10T14:15:18+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'freshowband'
primary_region = 'jnb'
console_command = '/code/manage.py shell'

[build]

[deploy]
  release_command = 'python manage.py migrate --noinput'

[env]
  PORT = '8000'

[processes]
  app = 'gunicorn --bind :8000 --workers 2 FRESHOWBAND.wsgi'
  celery = 'celery -A FRESHOWBAND worker --loglevel=INFO'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
